volumes:
  papra_data:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  stirling-pdf:
    container_name: stirling  
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    restart: unless-stopped    
    ports:
      - '8080:8080'
    volumes:
      - stirling_data:/usr/share/tessdata # Required for extra OCR languages
      - stirling_configs:/configs
      - stirling_files:/customFiles/
      - stirling_logs:/logs/
      - stirling_pipeline:/pipeline/
    labels:
      - "com.centurylinklabs.watchtower.enable=true"      
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB      
    networks:
      - reverse-proxy      