volumes:
  papra_data:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  app:
    image: ghcr.io/papra-hq/papra:latest
    container_name: papra
    restart: unless-stopped
    ports:
      - 1221:1221
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - APP_BASE_URL=https://papra.luigimicco.it
      - CLIENT_BASE_URL=https://papra.luigimicco.it
      - SERVER_BASE_URL=https://papra.luigimicco.it
      - AUTH_SECRET=KfKrkBned0A4RYr1JJJ93IGeuCACtuGvKCbVh4ByNR5XA54i
      - AUTH_IS_REGISTRATION_ENABLED=false
      - DOCUMENTS_OCR_LANGUAGES=eng,ita
    volumes:
      - papra_data:/app/app-data
    networks:
      - reverse-proxy