volumes:
  papra_data:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  app:
    image: ghcr.io/papra-hq/papra:latest-root
    container_name: papra
    hostname: papra
    ports:
      - "1221:1221"    
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - APP_BASE_URL=https://papra.luigimicco.it
      - CLIENT_BASE_URL=https://papra.luigimicco.it
      - SERVER_BASE_URL=https://papra.luigimicco.it
      - AUTH_SECRET=kJzxL7qCqsOUawlDTjWHxLrcyBJXVa9DZ7N3r02INNIkqcIK
      - AUTH_IS_REGISTRATION_ENABLED=true
      - DOCUMENTS_OCR_LANGUAGES=eng,ita
    volumes:
      - papra_data:/app/app-data
    networks:
      - reverse-proxy